# Joins and Linear Algebra

In [1]:
!pip install pandas numpy

Requirement already satisfied: pandas in c:\users\oi12b\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy in c:\users\oi12b\anaconda3\lib\site-packages (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\oi12b\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\oi12b\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\oi12b\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\oi12b\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd
import numpy as np

In [3]:
patients = pd.read_csv("data/patients.csv")
appointments = pd.read_csv("data/appointments.csv")

appointments.head()

,appointment_id,patient_id,doctor_name,appointment_date,appointment_time,reason,status
0,5001,1001,Dr. Smith,2026-02-01,09:00,Annual Physical,Completed
1,5002,1002,Dr. Smith,2026-02-01,10:00,Flu Symptoms,Completed
2,5003,1001,Dr. Lee,2026-02-15,14:30,Follow-up,Scheduled
3,5004,1003,Dr. Patel,2026-02-10,11:15,Blood Pressure,Completed
4,5005,1004,Dr. Smith,2026-02-18,16:00,Back Pain,Scheduled

In [4]:
patients.head()

   patient_id first_name last_name date_of_birth         phone      city
0        1001      Avery    Nguyen    1990-04-12  206-555-0143   Seattle
1        1002     Jordan    Rivera    1985-09-23  206-555-0198  Bellevue
2        1003      Samir     Patel    1978-01-30  425-555-0111   Redmond
3        1004      Elena    Garcia    2001-07-15  206-555-0177   Seattle
4        1005     Marcus   Johnson    1995-11-02  253-555-0182    Tacoma

## Inner Join
![Inner join](images/inner_join.png)
- Combines rows from two tables using a related column (called a key)
- Returns only rows where a match exists in both tables
  - Example: If you join two tables on a date column, only rows where the date appears in both tables are included
- Excludes any rows that do not have a matching value in the other table

In [12]:
patients_appointments = pd.merge(patients, appointments, on="patient_id", how="inner")
patients_appointments

,patient_id,first_name,last_name,date_of_birth,phone,city,appointment_id,doctor_name,appointment_date,appointment_time,reason,status
0,1001,Avery,Nguyen,1990-04-12,206-555-0143,Seattle,5001,Dr. Smith,2026-02-01,09:00,Annual Physical,Completed
1,1001,Avery,Nguyen,1990-04-12,206-555-0143,Seattle,5003,Dr. Lee,2026-02-15,14:30,Follow-up,Scheduled
2,1002,Jordan,Rivera,1985-09-23,206-555-0198,Bellevue,5002,Dr. Smith,2026-02-01,10:00,Flu Symptoms,Completed
3,1002,Jordan,Rivera,1985-09-23,206-555-0198,Bellevue,5006,Dr. Lee,2026-02-20,13:00,Lab Results,Scheduled
4,1003,Samir,Patel,1978-01-30,425-555-0111,Redmond,5004,Dr. Patel,2026-02-10,11:15,Blood Pressure,Completed
5,1004,Elena,Garcia,2001-07-15,206-555-0177,Seattle,5005,Dr. Smith,2026-02-18,16:00,Back Pain,Scheduled
6,1006,Linh,Tran,1988-03-19,206-555-0125,Seattle,5007,Dr. Patel,2026-02-22,15:45,Headache,Cancelled

## Your Turn! Inner Join

- Load the Student and Enrollment CSV files into pandas DataFrames
- Inspect both tables and identify the column they have in common
- Create an inner join between the two tables using that column
- Display the result and observe which rows were included and which were excluded

In [11]:
students = pd.read_csv("data/students.csv")
enrollments = pd.read_csv("data/enrollments.csv")
students_enrollments = pd.merge(students, enrollments, on="student_id", how="inner")
students_enrollments.head()

,student_id,first_name,last_name,email,program,start_year,enrollment_id,course_code,course_name,term,enroll_date,status
0,2001,Avery,Nguyen,avery.nguyen@example.edu,Computer Science,2024,9001,CSI101,Intro to Programming,2026-Winter,2026-01-06,Enrolled
1,2001,Avery,Nguyen,avery.nguyen@example.edu,Computer Science,2024,9005,CSI210,Data Structures,2026-Winter,2026-01-07,Enrolled
2,2002,Jordan,Rivera,jordan.rivera@example.edu,Data Science,2023,9002,CSI101,Intro to Programming,2026-Winter,2026-01-06,Enrolled
3,2003,Samir,Patel,samir.patel@example.edu,Cybersecurity,2022,9003,CSI210,Data Structures,2026-Winter,2026-01-07,Enrolled
4,2004,Elena,Garcia,elena.garcia@example.edu,Computer Science,2024,9004,CSI101,Intro to Programming,2026-Winter,2026-01-06,Dropped

# Left Join
![Left Join](images/left_join.png)
- Returns all records from the left table
- Only shows matching rows from the right table
- Displays None where there is no matching row in the right table

# Right Join
![Right Join](images/right_join.png)
- Returns all records from the right table
- Only shows matching rows from the left table
- Displays NaN for right table rows without a match

# Your Turn! Right and Left Join
- Perform a right join on enrollments and students
- Perform a left join on enrollments and students

In [22]:
students_ernollments_left = pd.merge(students, enrollments, how="left", on="student_id")
students_ernollments_right = pd.merge(students, enrollments, how="right", on="student_id")
students_ernollments_left

,student_id,first_name,last_name,email,program,start_year,enrollment_id,course_code,course_name,term,enroll_date,status
0,2001,Avery,Nguyen,avery.nguyen@example.edu,Computer Science,2024,9001.0,CSI101,Intro to Programming,2026-Winter,2026-01-06,Enrolled
1,2001,Avery,Nguyen,avery.nguyen@example.edu,Computer Science,2024,9005.0,CSI210,Data Structures,2026-Winter,2026-01-07,Enrolled
2,2002,Jordan,Rivera,jordan.rivera@example.edu,Data Science,2023,9002.0,CSI101,Intro to Programming,2026-Winter,2026-01-06,Enrolled
3,2003,Samir,Patel,samir.patel@example.edu,Cybersecurity,2022,9003.0,CSI210,Data Structures,2026-Winter,2026-01-07,Enrolled
4,2004,Elena,Garcia,elena.garcia@example.edu,Computer Science,2024,9004.0,CSI101,Intro to Programming,2026-Winter,2026-01-06,Dropped
5,2005,Marcus,Johnson,marcus.johnson@example.edu,Information Technology,2021,NaN,NaN,NaN,NaN,NaN,NaN
6,2006,Linh,Tran,linh.tran@example.edu,Data Science,2023,9006.0,DS201,Intro to Data Science,2026-Winter,2026-01-08,Enrolled
7,2007,Riley,Chen,riley.chen@example.edu,Computer Science,2022,9011.0,CSI210,Data Structures,2026-Winter,2026-01-07,Enrolled
8,2008,Fatima,Hassan,fatima.hassan@example.edu,Cybersecurity,2024,9007.0,CY110,Security Fundamentals,2026-Winter,2026-01-09,Enrolled
9,2009,Noah,Williams,noah.williams@example.edu,Information Technology,2023,9008.0,IT120,Networking Basics,2026-Winter,2026-01-10,Enrolled
10,2010,Amara,Singh,amara.singh@example.edu,Data Science,2024,9009.0,DS201,Intro to Data Science,2026-Winter,2026-01-08,Waitlisted
11,2011,Lucas,Martinez,lucas.martinez@example.edu,Computer Science,2021,NaN,NaN,NaN,NaN,NaN,NaN
12,2012,Zoe,Baker,zoe.baker@example.edu,Cybersecurity,2022,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
students_ernollments_right

,student_id,first_name,last_name,email,program,start_year,enrollment_id,course_code,course_name,term,enroll_date,status
0,2001,Avery,Nguyen,avery.nguyen@example.edu,Computer Science,2024.0,9001,CSI101,Intro to Programming,2026-Winter,2026-01-06,Enrolled
1,2002,Jordan,Rivera,jordan.rivera@example.edu,Data Science,2023.0,9002,CSI101,Intro to Programming,2026-Winter,2026-01-06,Enrolled
2,2003,Samir,Patel,samir.patel@example.edu,Cybersecurity,2022.0,9003,CSI210,Data Structures,2026-Winter,2026-01-07,Enrolled
3,2004,Elena,Garcia,elena.garcia@example.edu,Computer Science,2024.0,9004,CSI101,Intro to Programming,2026-Winter,2026-01-06,Dropped
4,2001,Avery,Nguyen,avery.nguyen@example.edu,Computer Science,2024.0,9005,CSI210,Data Structures,2026-Winter,2026-01-07,Enrolled
5,2006,Linh,Tran,linh.tran@example.edu,Data Science,2023.0,9006,DS201,Intro to Data Science,2026-Winter,2026-01-08,Enrolled
6,2008,Fatima,Hassan,fatima.hassan@example.edu,Cybersecurity,2024.0,9007,CY110,Security Fundamentals,2026-Winter,2026-01-09,Enrolled
7,2009,Noah,Williams,noah.williams@example.edu,Information Technology,2023.0,9008,IT120,Networking Basics,2026-Winter,2026-01-10,Enrolled
8,2010,Amara,Singh,amara.singh@example.edu,Data Science,2024.0,9009,DS201,Intro to Data Science,2026-Winter,2026-01-08,Waitlisted
9,2013,NaN,NaN,NaN,NaN,NaN,9010,CSI101,Intro to Programming,2026-Winter,2026-01-06,Enrolled
10,2007,Riley,Chen,riley.chen@example.edu,Computer Science,2022.0,9011,CSI210,Data Structures,2026-Winter,2026-01-07,Enrolled

# Outer Join
![Outer or Full Join](images/outer_join.png)
- Returns all rows
- Rows that do not match will have None for missing values

# Your Turn: Outer Join
- Create an outer Join on enrollments and students

In [20]:
students_enrollments_outer = pd.merge(students, enrollments, on='student_id', how='outer')
students_enrollments_outer

,student_id,first_name,last_name,email,program,start_year,enrollment_id,course_code,course_name,term,enroll_date,status
0,2001,Avery,Nguyen,avery.nguyen@example.edu,Computer Science,2024.0,9001.0,CSI101,Intro to Programming,2026-Winter,2026-01-06,Enrolled
1,2001,Avery,Nguyen,avery.nguyen@example.edu,Computer Science,2024.0,9005.0,CSI210,Data Structures,2026-Winter,2026-01-07,Enrolled
2,2002,Jordan,Rivera,jordan.rivera@example.edu,Data Science,2023.0,9002.0,CSI101,Intro to Programming,2026-Winter,2026-01-06,Enrolled
3,2003,Samir,Patel,samir.patel@example.edu,Cybersecurity,2022.0,9003.0,CSI210,Data Structures,2026-Winter,2026-01-07,Enrolled
4,2004,Elena,Garcia,elena.garcia@example.edu,Computer Science,2024.0,9004.0,CSI101,Intro to Programming,2026-Winter,2026-01-06,Dropped
5,2005,Marcus,Johnson,marcus.johnson@example.edu,Information Technology,2021.0,NaN,NaN,NaN,NaN,NaN,NaN
6,2006,Linh,Tran,linh.tran@example.edu,Data Science,2023.0,9006.0,DS201,Intro to Data Science,2026-Winter,2026-01-08,Enrolled
7,2007,Riley,Chen,riley.chen@example.edu,Computer Science,2022.0,9011.0,CSI210,Data Structures,2026-Winter,2026-01-07,Enrolled
8,2008,Fatima,Hassan,fatima.hassan@example.edu,Cybersecurity,2024.0,9007.0,CY110,Security Fundamentals,2026-Winter,2026-01-09,Enrolled
9,2009,Noah,Williams,noah.williams@example.edu,Information Technology,2023.0,9008.0,IT120,Networking Basics,2026-Winter,2026-01-10,Enrolled
10,2010,Amara,Singh,amara.singh@example.edu,Data Science,2024.0,9009.0,DS201,Intro to Data Science,2026-Winter,2026-01-08,Waitlisted
11,2011,Lucas,Martinez,lucas.martinez@example.edu,Computer Science,2021.0,NaN,NaN,NaN,NaN,NaN,NaN
12,2012,Zoe,Baker,zoe.baker@example.edu,Cybersecurity,2022.0,NaN,NaN,NaN,NaN,NaN,NaN
13,2013,NaN,NaN,NaN,NaN,NaN,9010.0,CSI101,Intro to Programming,2026-Winter,2026-01-06,Enrolled

# Concatenate vs Merge

**Merge**
- Combines two DataFrames based on columns or indexes

**Concatenate**
- Stacks DataFrames vertically or horizontally without needing a key

# Vertical Concatenation (Rows)

- Used to add more rows to an existing DataFrame
- Combines DataFrames by stacking them on top of each other
- Missing values are filled with None if a column exists in only one DataFrame

In [23]:
patients2 = pd.DataFrame({
    "patient_id": [1015, 1016, 1017, 1018, 1019],
    "first_name": ["Daniel", "Sofia", "Malik", "Hannah", "Victor"],
    "last_name": ["Lopez", "Anderson", "Brown", "Kim", "Alvarez"],
    "date_of_birth": ["1989-02-14", "1993-07-22", "1976-11-05", "2000-01-30", "1984-09-18"],
    "phone": [
        "206-555-0311",
        "425-555-0322",
        "253-555-0333",
        "206-555-0344",
        "425-555-0355"
    ],
    "city": ["Seattle", "Bellevue", "Tacoma", "Seattle", "Redmond"]
})

In [24]:
# What if there's different features?
patients2 = pd.DataFrame({
    "patient_id": [1015, 1016, 1017, 1018, 1019],
    "first_name": ["Daniel", "Sofia", "Malik", "Hannah", "Victor"],
    "last_name": ["Lopez", "Anderson", "Brown", "Kim", "Alvarez"],
    "date_of_birth": ["1989-02-14", "1993-07-22", "1976-11-05", "2000-01-30", "1984-09-18"],
    "phone": [
        "206-555-0311",
        "425-555-0322",
        "253-555-0333",
        "206-555-0344",
        "425-555-0355"
    ],
    "city": ["Seattle", "Bellevue", "Tacoma", "Seattle", "Redmond"],
    "insurance_provider": [
        "Premera",
        "Kaiser Permanente",
        "Regence",
        "Aetna",
        "Cigna"
    ]
})

# Horizontal Concatenation (Columns)
- Adds additional columns (features) to an existing DataFrame
- Combines DataFrames side-by-side
- Rows are aligned based on their index position

# Your Turn! Concatenation
- You are given a new dataframe students2
- Inspect the `students` and `students2` DataFrames
- Identify which column exists in `students2` but not in `students`
- Vertically concatenate the two DataFrames and store the result in a new variable called `all_students`
- Display `all_students`
- Horizontally concatenate the `students` and `enrollment` DataFrames and store the result in a variable called `horizontal_concat`
- Display `horizontal_concat`

In [30]:
students2 = pd.DataFrame({
    "student_id": [2013, 2014, 2015, 2016],
    "first_name": ["Diego", "Priya", "Ethan", "Maya"],
    "last_name": ["Santos", "Sharma", "Collins", "Desai"],
    "email": [
        "diego.santos@example.edu",
        "priya.sharma@example.edu",
        "ethan.collins@example.edu",
        "maya.desai@example.edu"
    ],
    "program": ["Computer Science", "Data Science", "Cybersecurity", "Information Technology"],
    "start_year": [2025, 2025, 2026, 2026],
    "gpa": [3.6, 3.9, 3.4, 3.8]
})

all_students = pd.concat([students, students2], axis= 0, ignore_index=True)
display(all_students)
horizontal_concat = pd.concat([students, enrollments], axis=1, ignore_index=True)
display(horizontal_concat)

,student_id,first_name,last_name,email,program,start_year,gpa
0,2001,Avery,Nguyen,avery.nguyen@example.edu,Computer Science,2024,NaN
1,2002,Jordan,Rivera,jordan.rivera@example.edu,Data Science,2023,NaN
2,2003,Samir,Patel,samir.patel@example.edu,Cybersecurity,2022,NaN
3,2004,Elena,Garcia,elena.garcia@example.edu,Computer Science,2024,NaN
4,2005,Marcus,Johnson,marcus.johnson@example.edu,Information Technology,2021,NaN
5,2006,Linh,Tran,linh.tran@example.edu,Data Science,2023,NaN
6,2007,Riley,Chen,riley.chen@example.edu,Computer Science,2022,NaN
7,2008,Fatima,Hassan,fatima.hassan@example.edu,Cybersecurity,2024,NaN
8,2009,Noah,Williams,noah.williams@example.edu,Information Technology,2023,NaN
9,2010,Amara,Singh,amara.singh@example.edu,Data Science,2024,NaN
10,2011,Lucas,Martinez,lucas.martinez@example.edu,Computer Science,2021,NaN
11,2012,Zoe,Baker,zoe.baker@example.edu,Cybersecurity,2022,NaN
12,2013,Diego,Santos,diego.santos@example.edu,Computer Science,2025,3.6
13,2014,Priya,Sharma,priya.sharma@example.edu,Data Science,2025,3.9
14,2015,Ethan,Collins,ethan.collins@example.edu,Cybersecurity,2026,3.4
15,2016,Maya,Desai,maya.desai@example.edu,Information Technology,2026,3.8

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,2001,Avery,Nguyen,avery.nguyen@example.edu,Computer Science,2024,9001.0,2001.0,CSI101,Intro to Programming,2026-Winter,2026-01-06,Enrolled
1,2002,Jordan,Rivera,jordan.rivera@example.edu,Data Science,2023,9002.0,2002.0,CSI101,Intro to Programming,2026-Winter,2026-01-06,Enrolled
2,2003,Samir,Patel,samir.patel@example.edu,Cybersecurity,2022,9003.0,2003.0,CSI210,Data Structures,2026-Winter,2026-01-07,Enrolled
3,2004,Elena,Garcia,elena.garcia@example.edu,Computer Science,2024,9004.0,2004.0,CSI101,Intro to Programming,2026-Winter,2026-01-06,Dropped
4,2005,Marcus,Johnson,marcus.johnson@example.edu,Information Technology,2021,9005.0,2001.0,CSI210,Data Structures,2026-Winter,2026-01-07,Enrolled
5,2006,Linh,Tran,linh.tran@example.edu,Data Science,2023,9006.0,2006.0,DS201,Intro to Data Science,2026-Winter,2026-01-08,Enrolled
6,2007,Riley,Chen,riley.chen@example.edu,Computer Science,2022,9007.0,2008.0,CY110,Security Fundamentals,2026-Winter,2026-01-09,Enrolled
7,2008,Fatima,Hassan,fatima.hassan@example.edu,Cybersecurity,2024,9008.0,2009.0,IT120,Networking Basics,2026-Winter,2026-01-10,Enrolled
8,2009,Noah,Williams,noah.williams@example.edu,Information Technology,2023,9009.0,2010.0,DS201,Intro to Data Science,2026-Winter,2026-01-08,Waitlisted
9,2010,Amara,Singh,amara.singh@example.edu,Data Science,2024,9010.0,2013.0,CSI101,Intro to Programming,2026-Winter,2026-01-06,Enrolled
10,2011,Lucas,Martinez,lucas.martinez@example.edu,Computer Science,2021,9011.0,2007.0,CSI210,Data Structures,2026-Winter,2026-01-07,Enrolled
11,2012,Zoe,Baker,zoe.baker@example.edu,Cybersecurity,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Column Space  
All possible linear combinations of the columns of a matrix.

In other words, the column space is every output you can create by scaling and adding the columns together.

---

### Rank  
- Rank is a nonnegative integer (0, 1, 2, …).  
- Each matrix has exactly one rank.  
- Rank tells you how many independent columns (or rows) the matrix has.  
- This also tells you the dimension of the column space.

---

### What does $A \in \mathbb{R}^{4 \times 3}$ Mean?
- 4x3 matrix 

### What does rank 3 Mean?
- Means that the 3 columns are independent 
- You can't create one column from combining the others 

### What does $v \in C(A)$ mean?

- $C(A)$: the column space of matrix A, meaning all possible outputs that can be created from the columns of A  
- $\in$: means "is an element of" or "belongs to"  
- $v$: the output vector  

So $v \in C(A)$ means the vector **v can be created by combining the columns of A**.

---

### What's the point of this?

This tells us whether a linear regression model can actually produce a given output.

Linear regression works by combining the columns of A (the features) with weights. If the real output vector is in the column space of A, then the model can produce it exactly. If it is not in the column space, then the model cannot produce it exactly, and there will always be some error.

In other words:  
**Can the real output be created by combining the features?**
Let's say you are trying to predict whether years of experience and level of education can accurately predict salary.

v represents the actual salaries (the real info from the data).

C(A) represents all possible salary predictions the model can produce using only years of experience and education.

If a real salary v is in C(A), then the model can predict it exactly.
If it is not in C(A), then the model can only approximate it.

In [31]:
colors = pd.read_csv("data/lego_database/colors.csv")
parts = pd.read_csv("data/lego_database/parts.csv")
sets = pd.read_csv("data/lego_database/sets.csv")
themes = pd.read_csv("data/lego_database/themes.csv")
inventories = pd.read_csv("data/lego_database/inventories.csv")
inventory_parts = pd.read_csv("data/lego_database/inventory_parts.csv")
inventory_sets = pd.read_csv("data/lego_database/inventory_sets.csv")
part_categories = pd.read_csv("data/lego_database/part_categories.csv")

In [51]:
total_inventory = pd.merge(inventory_sets, inventory_parts, on=['quantity','inventory_id'], how='outer')
total_inventory = pd.merge(total_inventory, inventories,on='set_num', how='outer').drop(columns='id')
total_inventory = pd.merge(total_inventory, colors, left_on='inventory_id', right_on='id', how='outer').drop(columns='id')
total_inventory = pd.merge(total_inventory, sets, on=['set_num', 'name'], how='outer')
total_inventory = pd.merge(total_inventory, parts, on=['part_num','name'], how='outer')
part_categories = part_categories.rename(columns={'id': 'part_cat_id'})
display(part_categories)
total_inventory = pd.merge(total_inventory, part_categories, on=['id','name'], how='outer')
# total_inventory = pd.merge(total_inventory, themes, left_on='theme_id', right_on='id', how='outer').drop(columns='id')
display(total_inventory)

    part_cat_id                                          name
0             1                                    Baseplates
1             2                                Bricks Printed
2             3                                 Bricks Sloped
3             4                       Duplo, Quatro and Primo
4             5                                Bricks Special
5             6                                 Bricks Wedged
6             7                                    Containers
7             8                                Technic Bricks
8             9                                Plates Special
9            10                                 Tiles Printed
10           11                                        Bricks
11           12                            Technic Connectors
12           13                                      Minifigs
13           14                                        Plates
14           15                                 Tiles Special
15           16                             Windows and Doors
16           17                                      Non-LEGO
17           18                   Hinges, Arms and Turntables
18           19                                         Tiles
19           20                        Bricks Round and Cones
20           21                       Plates Round and Dishes
21           22                                    Pneumatics
22           23                                        Panels
23           24                                         Other
24           25       Technic Steering, Suspension and Engine
25           26                               Technic Special
26           27                           Minifig Accessories
27           28                            Plants and Animals
28           29                              Wheels and Tyres
29           30                               Tubes and Hoses
30           31                       String, Bands and Reels
31           32                      Bars, Ladders and Fences
32           33                                          Rock
33           34                  Supports, Girders and Cranes
34           35                  Transportation - Sea and Air
35           36                         Transportation - Land
36           37                                 Bricks Curved
37           38              Flags, Signs, Plastics and Cloth
38           39                           Magnets and Holders
39           40                                Technic Panels
40           41       Bionicle, Hero Factory and Constraction
41           42                  Belville, Scala and Fabuland
42           43                                          Znap
43           44                                    Mechanical
44           45      Power Functions, Mindstorms and Electric
45           46                                 Technic Axles
46           47                      Windscreens and Fuselage
47           48                                       Clikits
48           49                                 Plates Angled
49           50                                      HO Scale
50           51                                 Technic Beams
51           52                                 Technic Gears
52           53                                  Technic Pins
53           54                                Technic Bushes
54           55                         Technic Beams Special
55           56                                         Tools
56           57  Non-Buildable Figures (Duplo, Fabuland, etc)

KeyError: 'id'

## AI Transparency Statement

AI tools were used to assist with grammar correction, formatting, and the creation of example datasets for demonstration purposes. All concepts, interpretations, and final content were created by me.