⠀⠀⠀⠀⠀⢀⣴⣶⣦⡄⢀⣀⣀⣀⣀⣀⢀⣴⣶⣦⣄⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⣿⣿⣿⠟⠉⠀⠀⠀⠀⠀⠀⠉⠛⢿⣿⣿⡄⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠙⠿⠁⠀⣠⣤⡄⠀⠀⢠⣤⣄⠀⠈⢿⠟⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠇⠀⢸⣿⣿⠳⣶⣶⡞⢿⣿⡇⢠⣼⢶⢶⣤⡀⠀⠀
⠀⠀⢀⣾⣿⣿⣿⣦⠈⠛⠋⠐⠤⠣⠀⠘⠛⠁⢿⡽⠛⠛⣼⡇⠀⠀
⠉⠉⠙⠿⢿⣿⡿⠟⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉

# Pandas 

Pandas are cute bears, and also the name of a powerful Python library for working with datasets, making it an essential tool in any data scientist’s toolkit.

Use cases:
- Work with tabular data and heterogenous data
- Cleaning messy datasets 

## Why it matters 
Data scientists spend 60–80% of their time cleaning and organizing data. This may seem excessive until you consider why. If you have bad “garbage” data, your analytics and models will produce bad “garbage” results. Garbage in, garbage out.

Pandas helps us with this by providing tools to fix errors, remove duplicates, and handle inconsistencies, all to improve analysis and model performance.

## What we are looking at this week
Before we hop into cleaning, we need to learn the basics of pandas. 
- Seriese, DataFrames, indices axes
- Creating & Accessing Data
- Transforming Data
- Summarizing Data

## What about Numpy?
Don't worry, your had work with Numpy last week will still pay off. Pandas and Numpy are used together, in fact Pandas is built on Numpy. 
- Numpy
  - Numerical 
  - Math
  - Array optomization 
- Pandas
  - Data analysis 
  - Data data manipulation
  - Optomizing tabular data

In [85]:
# Instalation 
!pip install pandas

Requirement already satisfied: pandas in /root/work/450DataDev/450DataScienceDevWinter2026LectureCode/Week4/.venv/lib/python3.10/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.22.4 in /root/work/450DataDev/450DataScienceDevWinter2026LectureCode/Week4/.venv/lib/python3.10/site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /root/work/450DataDev/450DataScienceDevWinter2026LectureCode/Week4/.venv/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /root/work/450DataDev/450DataScienceDevWinter2026LectureCode/Week4/.venv/lib/python3.10/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /root/work/450DataDev/450DataScienceDevWinter2026LectureCode/Week4/.venv/lib/python3.10/site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /root/work/450DataDev/450DataScienceDevWinter2026LectureCode/Week4/.venv/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [86]:
#Import 
import pandas as pd
import numpy as np

## Seriese
- One dimensinal array 
- All elements must be the same data type
- Think of it like a column on a table 
- Fixed lengeth 
- Single direction 
- Index Lables if nothing else is specified

In [87]:
# Series
# Defult index as Label
nums = pd.Series([1,2,3,4])
print(nums)
print(nums[0])

#Create your own lable
names = ["rose", "Ix", "Eric"]
users = pd.Series(names, index = ["C", "H", "H"])
print(users)
print(users["C"])

menu_prices = pd.Series({
    "Coffee": 3.50,
    "Tea": 2.75,
    "Sandwich": 6.25,
    "Salad": 5.50,
    "Cookie": 1.75
})

print(menu_prices["Tea"])
menu_prices

0    1
1    2
2    3
3    4
dtype: int64
1
C    rose
H      Ix
H    Eric
dtype: object
rose
2.75

Coffee      3.50
Tea         2.75
Sandwich    6.25
Salad       5.50
Cookie      1.75
dtype: float64

## Values and Index
- .value will return the values in a 2d array
- .index retruns lables

In [88]:
print(menu_prices.values)
print(menu_prices.index)

print("no predefined index lables: ", nums.index)

[3.5  2.75 6.25 5.5  1.75]
Index(['Coffee', 'Tea', 'Sandwich', 'Salad', 'Cookie'], dtype='object')
no predefined index lables:  RangeIndex(start=0, stop=4, step=1)

## Update 
- .update is used to update a value in a Series

In [89]:
#Update One
seattle_temperature = pd.Series([49, 49, None, 50, 54])
seattle_temperature.update(pd.Series([49], index=[2]))

seattle_temperature

0    49.0
1    49.0
2    49.0
3    50.0
4    54.0
dtype: float64

In [ ]:
#Update Multiple 
seattle_temperature = pd.Series([49, 49, None, 50, 54, None])
seattle_temperature.update(pd.Series([49, 55], index=[2,5]))
seattle_temperature

0    49.0
1    49.0
2    49.0
3    50.0
4    54.0
5    55.0
dtype: float64

## Updaing index lables
- .rename will update an index lable

In [91]:
seattle_temp = pd.Series(
    [48, 50, 52, 49, 47, 51, 53],
    index=["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
)
seattle_temp_short = seattle_temp.rename({
    "Mon": "M",
    "Tue": "Tu",
    "Wed": "W",
    "Thu": "Th",
    "Fri": "F",
    "Sat": "Sa",
    "Sun": "Su"
})
print("Seattle Temp", seattle_temp)
print("Short Temp", seattle_temp_short)

Seattle Temp Mon    48
Tue    50
Wed    52
Thu    49
Fri    47
Sat    51
Sun    53
dtype: int64
Short Temp M     48
Tu    50
W     52
Th    49
F     47
Sa    51
Su    53
dtype: int64

In [92]:
#Inplace 
seattle_temp = pd.Series(
    [48, 50, 52, 49, 47, 51, 53],
    index=["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
)
seattle_temp_short = seattle_temp.rename({
    "Mon": "M",
    "Tue": "Tu",
    "Wed": "W",
    "Thu": "Th",
    "Fri": "F",
    "Sat": "Sa",
    "Sun": "Su"
}, inplace=True)
#Changes the original 
print("Seattle Temp", seattle_temp)
#Does NOT make a copy 
print("Short Temp", seattle_temp_short)

Seattle Temp M     48
Tu    50
W     52
Th    49
F     47
Sa    51
Su    53
dtype: int64
Short Temp None

## Your Turn! 
Create a Pandas Series with:
- At least 5 values
- At least 2 missing values (None)
- Clear, meaningful index labels
- Print:
  - The index of the Series
  - The values of the Series
- Update the index labels so they mean something different or are formatted differently. Ex Monday, Tuseday to M, T or Small, Medium to S, M

## Data Frames 
Data frames are the most used datastructure provided by pandas. 
- Two-dimensional data structure, like a table, with rows representing records and columns representing features.

In [93]:
walkability = pd.DataFrame({
    "City": ["Seattle", "New York", "Los Angeles", "Chicago", "Phoenix"],
    "Walkability": ["High", "Very High", "Medium", "High", "Low"]
})
# Notebooks will even provide a pretty table!
walkability

          City Walkability
0      Seattle        High
1     New York   Very High
2  Los Angeles      Medium
3      Chicago        High
4      Phoenix         Low

In [94]:
#Other ways to make DataFrames
df = pd.DataFrame([
    {"City": "Seattle", "Walkability": "High"},
    {"City": "New York", "Walkability": "Very High"},
    {"City": "Chicago", "Walkability": "High"}
])
df

       City Walkability
0   Seattle        High
1  New York   Very High
2   Chicago        High

In [95]:
data = [
    ["Seattle", "High"],
    ["New York", "Very High"],
    ["Chicago", "High"]
]

df = pd.DataFrame(data, columns=["City", "Walkability"])
df

       City Walkability
0   Seattle        High
1  New York   Very High
2   Chicago        High

In [96]:
data = np.array([
    ["Seattle", "High"],
    ["New York", "Very High"],
    ["Chicago", "High"]
])

df = pd.DataFrame(data, columns=["City", "Walkability"])
df

       City Walkability
0   Seattle        High
1  New York   Very High
2   Chicago        High

In [97]:
cities = pd.Series(["Seattle", "New York", "Chicago"])
walkability = pd.Series(["High", "Very High", "High"])

df = pd.DataFrame({
    "City": cities,
    "Walkability": walkability
})
df

       City Walkability
0   Seattle        High
1  New York   Very High
2   Chicago        High

## Other ways to create DataFrames
- CSV file 
- Excel file
- Json

# Axis 
Like with our np arrays our DF have Axis
- rows axis 0
- columns axis 1

# Indexing 
- DataFrames use indexing in a similar way to Series.

In [98]:

df = pd.DataFrame(
    {
        "Walkability": ["High", "Very High", "High", "Low"],
        "TransitScore": [85, 90, 78, 50],
        "BikeScore": [70, 80, 65, 40]
    })

df.index = ["Seattle", "New York", "Chicago", "Phoenix"]

df

         Walkability  TransitScore  BikeScore
Seattle         High            85         70
New York   Very High            90         80
Chicago         High            78         65
Phoenix          Low            50         40

In [99]:

df = pd.DataFrame(
    {
        "Walkability": [
            "High", "Very High", "High", "Low",
            "High", "Medium", "High"
        ],
        "TransitScore": [
            85, 90, 78, 50,
            60, 55, 65
        ],
        "BikeScore": [
            70, 80, 65, 40,
            85, 70, 80
        ]
    },
    index=[
        "Seattle", "New York", "Chicago", "Phoenix",
        "Portland", "Boulder", "Madison"
    ]
)

df

# Rename can be used to update index values
df.rename(index={"New York": "NYC"}, inplace=True)

df

         Walkability  TransitScore  BikeScore
Seattle         High            85         70
NYC        Very High            90         80
Chicago         High            78         65
Phoenix          Low            50         40
Portland        High            60         85
Boulder       Medium            55         70
Madison         High            65         80

## Accessing data
- Columns
  - bracket notation df["column"]
  - dot notation df.column
- rows
  - By lable df.loc["index lable"]
  - by position df.iloc[0]

In [100]:
print(df["TransitScore"])
print()
print(df.TransitScore)
print()
print(df.loc["Seattle"])
print(df.iloc[0])

Seattle     85
NYC         90
Chicago     78
Phoenix     50
Portland    60
Boulder     55
Madison     65
Name: TransitScore, dtype: int64

Seattle     85
NYC         90
Chicago     78
Phoenix     50
Portland    60
Boulder     55
Madison     65
Name: TransitScore, dtype: int64

Walkability     High
TransitScore      85
BikeScore         70
Name: Seattle, dtype: object
Walkability     High
TransitScore      85
BikeScore         70
Name: Seattle, dtype: object

In [101]:
# Adding new Columns
df["PopulationMillions"] = [0.75, 8.3, 2.7, 1.6, 0.65, 0.11, 0.27]
df

         Walkability  TransitScore  BikeScore  PopulationMillions
Seattle         High            85         70                0.75
NYC        Very High            90         80                8.30
Chicago         High            78         65                2.70
Phoenix          Low            50         40                1.60
Portland        High            60         85                0.65
Boulder       Medium            55         70                0.11
Madison         High            65         80                0.27

## Performing math on columns
DataFrames allow math operations to be performed on a single or entire columns using other columns.

In [117]:
#Single Column
print(df["TransitScore"].sum())

#Multiple Columns
print(df[["TransitScore", "BikeScore"]].sum())

#Find max
print(df["PopulationMillions"].idxmax())

483
TransitScore    483
BikeScore       490
dtype: int64
NYC

## Operations on entire columns

In [102]:
df["AvgTransport"] = (df["TransitScore"] + df["BikeScore"]) / 2
print(df["AvgTransport"])

Seattle     77.5
NYC         85.0
Chicago     71.5
Phoenix     45.0
Portland    72.5
Boulder     62.5
Madison     72.5
Name: AvgTransport, dtype: float64

In [103]:
bike_per_million = df["BikeScore"] / df["PopulationMillions"]
bike_per_million

Seattle      93.333333
NYC           9.638554
Chicago      24.074074
Phoenix      25.000000
Portland    130.769231
Boulder     636.363636
Madison     296.296296
dtype: float64

## Your Turn: DataFrames
Part 1: Create a DataFrame usin gthe following wild fild data
     <!-- 
        "FireName": ["Pine Ridge", "Cedar Creek", "Skyline", "Red Canyon", "Bear Hollow"],
        "State": ["WA", "OR", "CA", "ID", "MT"],
        "AcresBurned": [1200, 5400, 23000, 800, 12750],
        "ContainmentPct": [65, 40, 25, 90, 55],
        "HomesThreatened": [18, 120, 640, 5, 210],
        "Firefighters": [120, 420, 980, 60, 510] -->
Part 2:
  - Show the Achres per firefighter 
  - Add a new column to the DF called uncontained, it should show the % of fire that's not contained, for example if ContainmentPct is 40 uncontained should be 60

In [104]:
#Answer
wildfires = pd.DataFrame(
    {
        "FireName": ["Pine Ridge", "Cedar Creek", "Skyline", "Red Canyon", "Bear Hollow"],
        "State": ["WA", "OR", "CA", "ID", "MT"],
        "AcresBurned": [1200, 5400, 23000, 800, 12750],
        "ContainmentPct": [65, 40, 25, 90, 55],
        "HomesThreatened": [18, 120, 640, 5, 210],
        "Firefighters": [120, 420, 980, 60, 510]
    }
)

# Part 2: Acres per firefighter
acres_per_fire_fighter = (
    wildfires["AcresBurned"] / wildfires["Firefighters"]
)
print(acres_per_fire_fighter)
# Part 2: Uncontained percentage
wildfires["UncontainedPct"] = 100 - wildfires["ContainmentPct"]

print(wildfires)

0    10.000000
1    12.857143
2    23.469388
3    13.333333
4    25.000000
dtype: float64
      FireName State  AcresBurned  ContainmentPct  HomesThreatened  \
0   Pine Ridge    WA         1200              65               18
1  Cedar Creek    OR         5400              40              120
2      Skyline    CA        23000              25              640
3   Red Canyon    ID          800              90                5
4  Bear Hollow    MT        12750              55              210

   Firefighters  UncontainedPct
0           120              35
1           420              60
2           980              75
3            60              10
4           510              45

# Transposing 
- .T will swap the rows and columns

In [105]:
wildfires.T

                          0            1        2           3            4
FireName         Pine Ridge  Cedar Creek  Skyline  Red Canyon  Bear Hollow
State                    WA           OR       CA          ID           MT
AcresBurned            1200         5400    23000         800        12750
ContainmentPct           65           40       25          90           55
HomesThreatened          18          120      640           5          210
Firefighters            120          420      980          60          510
UncontainedPct           35           60       75          10           45

In [106]:
df.T

                   Seattle        NYC Chicago Phoenix Portland Boulder Madison
Walkability           High  Very High    High     Low     High  Medium    High
TransitScore            85         90      78      50       60      55      65
BikeScore               70         80      65      40       85      70      80
PopulationMillions    0.75        8.3     2.7     1.6     0.65    0.11    0.27
AvgTransport          77.5       85.0    71.5    45.0     72.5    62.5    72.5

# Soirting Columns
- .sort_values will sort rows based on a column

In [107]:
df.sort_values(by="TransitScore", ascending=False)

,Walkability,TransitScore,BikeScore,PopulationMillions,AvgTransport
NYC,Very High,90,80,8.30,85.0
Seattle,High,85,70,0.75,77.5
Chicago,High,78,65,2.70,71.5
Madison,High,65,80,0.27,72.5
Portland,High,60,85,0.65,72.5
Boulder,Medium,55,70,0.11,62.5
Phoenix,Low,50,40,1.60,45.0

In [108]:
df.sort_values(by="BikeScore")

,Walkability,TransitScore,BikeScore,PopulationMillions,AvgTransport
Phoenix,Low,50,40,1.60,45.0
Chicago,High,78,65,2.70,71.5
Seattle,High,85,70,0.75,77.5
Boulder,Medium,55,70,0.11,62.5
NYC,Very High,90,80,8.30,85.0
Madison,High,65,80,0.27,72.5
Portland,High,60,85,0.65,72.5

# Filtering
- Rows can be filtered using logic operators

In [109]:
df[df["TransitScore"] > 80]

        Walkability  TransitScore  BikeScore  PopulationMillions  AvgTransport
Seattle        High            85         70                0.75          77.5
NYC       Very High            90         80                8.30          85.0

In [110]:
# Multiple conditions
df[(df["TransitScore"] > 80) & (df["BikeScore"] > 70)]

    Walkability  TransitScore  BikeScore  PopulationMillions  AvgTransport
NYC   Very High            90         80                 8.3          85.0

In [113]:
df["TransitOverBike"]= df["TransitScore"] > df["BikeScore"]
df

,Walkability,TransitScore,BikeScore,PopulationMillions,AvgTransport,TransitOverBike
Seattle,High,85,70,0.75,77.5,True
NYC,Very High,90,80,8.30,85.0,True
Chicago,High,78,65,2.70,71.5,True
Phoenix,Low,50,40,1.60,45.0,True
Portland,High,60,85,0.65,72.5,False
Boulder,Medium,55,70,0.11,62.5,False
Madison,High,65,80,0.27,72.5,False

In [114]:
df["TransitOverBike"] = df["TransitOverBike"].map({
  True:"Transit",
  False:"Bike"
})
df

,Walkability,TransitScore,BikeScore,PopulationMillions,AvgTransport,TransitOverBike
Seattle,High,85,70,0.75,77.5,Transit
NYC,Very High,90,80,8.30,85.0,Transit
Chicago,High,78,65,2.70,71.5,Transit
Phoenix,Low,50,40,1.60,45.0,Transit
Portland,High,60,85,0.65,72.5,Bike
Boulder,Medium,55,70,0.11,62.5,Bike
Madison,High,65,80,0.27,72.5,Bike

## Your Turn: Filtering 
Complete the following using your wildfire dataframe
- Fires that have burned more than 10,000 acres
- Fires with less than 50% containment
- Fires where more than 100 homes are threatened
- Fires that:
  - Have burned more than 10,000 acres
  - AND have less than 50% containment

In [118]:
#Answer
print(wildfires["AcresBurned"] > 10000)

print(wildfires["ContainmentPct"] < 50)

print([wildfires["HomesThreatened"] > 100])

print([
    (wildfires["AcresBurned"] > 10000) &
    (wildfires["ContainmentPct"] < 50)
])

0    False
1    False
2     True
3    False
4     True
Name: AcresBurned, dtype: bool
0    False
1     True
2     True
3    False
4    False
Name: ContainmentPct, dtype: bool
[0    False
1     True
2     True
3    False
4     True
Name: HomesThreatened, dtype: bool]
[0    False
1    False
2     True
3    False
4    False
dtype: bool]

AI Transparency Statement
AI tools were used to assist with formatting, grammar and generating example data.